### ISSUE TITLE
IA Conflict

### ISSUE THREAD

**Issue by ampaddon** [LoneDev6/IAServerMonitor#1]
There is a conflict with IA ServerMonitor, and IA Boss Integration.  When you have both of them on, the ram option does not work, and the icons do not load in the boss shop.  I'm not sure who is to blame for this, so if you want to contact the other developer and work together to get it to work, that would be epic.

Also running latest IA, IA Sever Monitor, and IA Boss Shop, as two of those there are only 1 iteration.

Thank you in advanced for looking into this.

**Comment by LoneDev6** [comment]
do you get any error in console?
can you send screenshots?

anyway, i'm not the dev of the boss shop plugin

**Comment by ampaddon** [comment]
here is the only error.
http://prntscr.com/seypw7

gui with server monitor installed..
![image](https://user-images.githubusercontent.com/61991408/81616604-2b6d3980-93ba-11ea-9726-9643012bc5b8.png)

![image](https://user-images.githubusercontent.com/61991408/81617034-062cfb00-93bb-11ea-80d6-932d7cea4abc.png)


i think it is your cpu graph that might be interfering, as the ram only works in this scenario when the server has no cpu monitoring

**Comment by LoneDev6** [comment]
So basically if you have Bosshop addon installed and the ServerMonitor you'd see this strange line on screen?

**Comment by ampaddon** [comment]
no, the boss shop plugin crashes the cpu, ability to monitor both server monitor's ram.  the server monitor in return refuses to let boss shop see the textures, thus it is its a mass possibly the cpu monitor bug.

**Comment by LoneDev6** [comment]
I tested the plugin and everything works fine.
Please update IA to the new update (i will release it today) and let me know.

Reopen this issue if you still have problems after updating
